закончил 2 урок
ArIonMark1/Django_Shop pull request #2
Opened 2021-05-30 17:21 UTC by ArIonMark1

сложно было с импортом товара у вьюху

2021-05-31 07:11 UTC, Vokler requested changes

2021-05-31 07:11 UTC, Vokler commented on mainapp/templates/mainapp/products.html
> +{##}
Лучше удалить закомментированный кусок. Он все равно не понадобится

2021-05-31 07:11 UTC, Vokler commented on mainapp/templates/mainapp/products.html
> +                {% for el in products %}
Лучше называть переменные более понятно, чтобы в дальнейшем было понятно, что такое `el`.

2021-05-31 07:11 UTC, Vokler commented on geekshop/urls.py
> +    path('', index, name="index"),
Придерживайтесь везде единого стиля кавычек

2021-06-01 07:25 UTC, ArIonMark1 commented on mainapp/templates/mainapp/products.html
> +{##}
окей, просто оставил вдруг что сломается, что бы легче было восстановить и забыл про него)
Удалил

2021-06-01 07:26 UTC, ArIonMark1 commented on geekshop/urls.py
> +    path('', index, name="index"),
заменил, кажись все нашел

2021-06-01 18:12 UTC, Vokler approved these changes

2021-06-01 18:12 UTC, merged